
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action OptionsAction;
	private global::Gtk.Action WaitingRoomAction;
	private global::Gtk.Action WaitingRoomAction1;
	private global::Gtk.Action HomeAction;
	private global::Gtk.Action TopAction;
	private global::Gtk.Action HotnessAction;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action UploadAction1;
	private global::Gtk.Action ExitAction1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.VBox vbox3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.OptionsAction = new global::Gtk.Action ("OptionsAction", global::Mono.Unix.Catalog.GetString ("Options"), null, null);
		this.OptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Options");
		w1.Add (this.OptionsAction, null);
		this.WaitingRoomAction = new global::Gtk.Action ("WaitingRoomAction", global::Mono.Unix.Catalog.GetString ("Waiting room"), null, null);
		this.WaitingRoomAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Waiting room");
		w1.Add (this.WaitingRoomAction, null);
		this.WaitingRoomAction1 = new global::Gtk.Action ("WaitingRoomAction1", global::Mono.Unix.Catalog.GetString ("Waiting room"), null, null);
		this.WaitingRoomAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Waiting room");
		w1.Add (this.WaitingRoomAction1, null);
		this.HomeAction = new global::Gtk.Action ("HomeAction", global::Mono.Unix.Catalog.GetString ("Home"), null, null);
		this.HomeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Home");
		w1.Add (this.HomeAction, null);
		this.TopAction = new global::Gtk.Action ("TopAction", global::Mono.Unix.Catalog.GetString ("Top"), null, null);
		this.TopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Top");
		w1.Add (this.TopAction, null);
		this.HotnessAction = new global::Gtk.Action ("HotnessAction", global::Mono.Unix.Catalog.GetString ("Hotness"), null, null);
		this.HotnessAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Hotness");
		w1.Add (this.HotnessAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.UploadAction1 = new global::Gtk.Action ("UploadAction1", global::Mono.Unix.Catalog.GetString ("Upload"), null, null);
		this.UploadAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Upload");
		w1.Add (this.UploadAction1, null);
		this.ExitAction1 = new global::Gtk.Action ("ExitAction1", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Project");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.AllowShrink = true;
		this.DefaultWidth = 700;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='UploadAction1' action='UploadAction1'/><menuitem name='ExitAction1' action='ExitAction1'/></menu><menu name='OptionsAction' action='OptionsAction'><menuitem name='HomeAction' action='HomeAction'/><menuitem name='TopAction' action='TopAction'/><menuitem name='HotnessAction' action='HotnessAction'/><menuitem name='WaitingRoomAction1' action='WaitingRoomAction1'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
		w3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		w3.Add (this.vbox3);
		this.GtkScrolledWindow.Add (w3);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w6.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.WaitingRoomAction1.Activated += new global::System.EventHandler (this.OnWaitingRoomAction1Activated);
		this.HomeAction.Activated += new global::System.EventHandler (this.OnHomeActionActivated);
		this.TopAction.Activated += new global::System.EventHandler (this.OnTopActionActivated);
		this.HotnessAction.Activated += new global::System.EventHandler (this.OnHotnessActionActivated);
		this.UploadAction1.Activated += new global::System.EventHandler (this.OnUploadAction1Activated);
		this.ExitAction1.Activated += new global::System.EventHandler (this.OnExitAction1Activated);
	}
}
