
// This file has been generated by the GUI designer. Do not modify.
namespace Project
{
	public partial class ImgWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label2;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.VBox vbox3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Project.ImgWindow
			this.Name = "Project.ImgWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ImgWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 700;
			this.DefaultHeight = 600;
			// Container child Project.ImgWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport ();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			w2.Add (this.vbox3);
			this.scrolledwindow1.Add (w2);
			this.vbox2.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.scrolledwindow1]));
			w5.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
